name: g7trailapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.14.0 <3.0.0"
dependencies:
  ac_inet_connectivity_checker: ^0.1.6
  auto_size_text: ^3.0.0
  beacon_scanner: ^0.0.4
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.17.4
  cupertino_icons: ^1.0.8
  firebase_analytics: ^10.10.6
  firebase_auth: ^4.19.6
  firebase_core: ^2.31.1
  firebase_messaging: ^14.9.3
  firebase_remote_config: ^4.4.6
  firebase_storage: ^11.7.6
  flutter_beacon: ^0.5.1
  flutter_cache_manager: ^3.3.0
  flutter_google_street_view: any
  flutter_html: ^3.0.0-beta.2
  flutter_local_notifications: ^17.1.2
  flutter_settings_ui: ^3.0.1
  flutter_signin_button: ^2.0.0
  flutter_tts: ^4.0.2
  fluttertoast: ^8.2.5
  font_awesome_flutter: ^9.2.0
  get_it: ^7.7.0
  global_configuration: ^2.0.0
  google_maps_flutter: any
  google_sign_in: ^6.2.1
  http: ^1.2.1
  intl: ^0.19.0
  introduction_screen: ^3.1.14
  overlay_support: ^2.1.0
  package_info_plus: ^8.0.0
  password_strength: ^0.2.0
  provider: ^6.1.2
  pubspec_dependency_sorter: ^1.0.4
  shared_preferences: ^2.2.3
  simple_animations: ^5.0.2
  sliding_up_panel: ^2.0.0+1
  the_apple_sign_in: ^1.1.1
  timezone: ^0.9.3
  url_launcher: ^6.2.6
  vibration: ^1.9.0
  video_player: ^2.8.6
  workmanager: ^0.5.2
  flutter:
    sdk: flutter
  flutter_config: ^2.0.2
dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
flutter_icons:
  android: launcher_icon
  image_path: assets/images/app-icon.png
  ios: true
flutter:
  assets:
    - assets/images/
    - assets/images/destinations/
    - assets/fonts/
    - assets/fonts/LouisGeorgeCafe/
  fonts:
    - family: LGCafe
      fonts:
        - asset: assets/fonts/LouisGeorgeCafe/LouisGeorgeCafe.ttf
          weight: 400
        - asset: assets/fonts/LouisGeorgeCafe/LouisGeorgeCafeItalic.ttf
          style: italic
        - asset: assets/fonts/LouisGeorgeCafe/LouisGeorgeCafeBold.ttf
          weight: 800
        - asset: assets/fonts/LouisGeorgeCafe/LouisGeorgeCafeLight.ttf
          weight: 200
  uses-material-design: true
