// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxvv1pIxcYTaaqX7jJRzIKVaAYv91ij7s',
    appId: '1:1063785186004:android:5491ee9628d255b9f33141',
    messagingSenderId: '1063785186004',
    projectId: 'group-of-seven-trail',
    storageBucket: 'group-of-seven-trail.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWavRzJeivPw32lhn3TfOojTnyAKyufnk',
    appId: '1:1063785186004:ios:e56d62d750ba29fef33141',
    messagingSenderId: '1063785186004',
    projectId: 'group-of-seven-trail',
    storageBucket: 'group-of-seven-trail.appspot.com',
    androidClientId: '1063785186004-98avi1iagnp46ncj3kig8qg63i6raj2a.apps.googleusercontent.com',
    iosClientId: '1063785186004-4tcivveibsmlooqn6i6dh037qhb3t7mr.apps.googleusercontent.com',
    iosBundleId: 'com.groupofseven.g7trailapp',
  );
}
